python-xlib/python-xlib

Xlib/protocol/rq.py, test/test_events_le.py, test/test_requests_le.py
This makes some progress in getting the tests running. The next hurdle is the use of `buffer`, which is gone in Python 3. The replacement is `memoryview`, but the API is a bit different. I may look into that tomorrow.
=> Some more Python 3 fixes

Xlib/protocol/rq.py
`Struct.to_binary`, `Struct.parse_value` and `Struct.parse_binary` were doing code generation to produce and store a specialised method for each struct instance. Apparently (see #12) this was a necessary optimisation in the distant past, but it's almost certainly no longer needed, and it makes the code considerably harder to follow.
On my machine the tests run slightly but noticeably faster with this change, but of course the tests are probably not a realistic sample for performance testing.
This doesn't directly impact Python 3 support, but it simplifies things.
=> Eliminate code generation for Struct methods

Xlib/error.py, Xlib/protocol/rq.py, Xlib/rdb.py, Xlib/support/connect.py, Xlib/support/unix_connect.py, Xlib/xobject/colormap.py, Xlib/xobject/drawable.py, test/gen/genprottest.py, test/test_events_be.py, test/test_events_le.py, test/test_requests_be.py, test/test_requests_le.py
This adds +4 tests passed on Py3.
Next step would be unicode/str/bytes clarification for both Pythons using `from __future__ import unicode_literals` (seems the most annoying thing).
=> Get rid of string module functions, reduce types module usage

README.md, Xlib/protocol/request.py, Xlib/protocol/rq.py, Xlib/rdb.py, Xlib/support/unix_connect.py, Xlib/xobject/colormap.py, Xlib/xobject/drawable.py, examples/childwin.py, examples/shapewin.py, test/gen/genprottest.py, test/test_events_be.py, test/test_events_le.py, test/test_requests_be.py, test/test_requests_le.py, utils/parsexbug.py
The fixes reduce Py3 test failures from `(failures=40, errors=207)` to `(failures=47, errors=11)`.
* `apply()` is finally removed
* integer division `/` is replaced with `//`
* `pack_value()` methods use `bytes` almost everywhere
* `atoi()` is replaced with `int()`
* `ord()` is called for Python 2 only (because `bytes` element is already an integer in Py3)
* direct `str()` usage for `bytes` is reduced because `str(b'bytes')` leads to `"b'bytes'"`, not `"bytes"`
=> Fix a lot of Python 3 issues

examples/run_examples.py
I had a little trouble running nosetests locally.
If `/usr/bin/env python` is configured to be e.g. `/usr/bin/python3.4`, then `run_examples.py` will run its subprocess scripts using python3.4 even though `run_examples.py` was run using python2.7.
This pull request fixes this issue by prepending `sys.executable` to the subprocess command.
Before:
```
$ python2.7 examples/run_examples.py
```
After:
```
$ python2.7 examples/run_examples.py
....
----------------------------------------------------------------------
Ran 4 tests in 10.839s
OK
```
=> Make run_examples.py run the scripts with proper interpreter

Xlib/ext/record.py
Fix exception when using record extension:
```
TypeError: Object value must be tuple, dictionary or DictWrapper: 0
```
=> record: fix extension (without changing API)

Xlib/protocol/display.py
Make sure we start a new iteration of the parse_response loop upon handling a response, so the code does not try to parse left over received data based on the previous request type.
=> protocol: fix handling of generic events

Xlib/support/vms_connect.py
Fix an error that comes up when byte-compiling the code during install:
```
byte-compiling build/bdist.linux-x86_64/egg/Xlib/support/vms_connect.py to vms_connect.cpython-35.pyc
File "build/bdist.linux-x86_64/egg/Xlib/support/vms_connect.py", line 63
except socket.error, val:
^
SyntaxError: invalid syntax
```
=> support/vms_connect: fix invalid Python 3 syntax

.travis.yml
Make sure nosetest pick up all our tests in test/, including those present in executable files.
Before:
```
nose.selector: INFO: /home/travis/build/benoit-pierre/python-xlib/test/test_events_be.py is executable; skipped
nose.selector: INFO: /home/travis/build/benoit-pierre/python-xlib/test/test_events_le.py is executable; skipped
nose.selector: INFO: /home/travis/build/benoit-pierre/python-xlib/test/test_manual.py is executable; skipped
nose.selector: INFO: /home/travis/build/benoit-pierre/python-xlib/test/test_rdb.py is executable; skipped
nose.selector: INFO: /home/travis/build/benoit-pierre/python-xlib/test/test_requests_le.py is executable; skipped
[...]
Ran 44 tests in 15.906s
```
After:
```
Ran 459 tests in 13.435s
```
=> travis: fix command to run tests

Xlib/ext/security.py, Xlib/protocol/event.py, Xlib/protocol/rq.py, test/__init__.py, test/test_struct.py
Rename rq.Bytes to rq.Binary and rq.FixedString to rq.FixedBinary so it's clear what those fields are used for.
The new `test_struct` tests are for checking `protocol.rq.Struct` support for the different fields in a more directed way then `test_requests/test_events`.
=> cleanup binary strings support and add some tests

.travis.yml
Will automatically deploy to GitHub/PyPi when a new tag is pushed to master.
Credentials need to be filled-in:
- for GitHub, a new access token must be created (in GitHub settings / Personal access tokens) and encrypted with Travis CLI tool: `travis encrypt`
- similarly, the user/password field must be filled for PyPi (with again the password encrypted with `travis encrypt`)
Note: make sure the (clear text version of the) PyPi password does not contain a `%`, or it will trigger an exception and leak the password in the logs!
=> add GitHub and PyPi deployments to Travis CI configuration

Xlib/protocol/display.py
Don't try to access `sequence_number` member for those events, since they [don't have one](https://github.com/python-xlib/python-xlib/blob/master/Xlib/protocol/event.py#L393).
=> protocol/display: fix handling of KeymapNotify events

.travis.yml
Switch to tar.bz2 as tar.xz is not supported by PyPI.
=> travis: change source distribution format

Xlib/ext/record.py, examples/record_demo.py
Fixes the following traceback when running under Python 3.5
Confirmed it's still working under Python 2.7
```
[osboxes@osboxes QMouseKeys]$ python record_demo.py
RECORD extension version 1.13
Traceback (most recent call last):
File "record_demo.py", line 105, in <module>
record_dpy.record_enable_context(ctx, record_callback)
File "/usr/lib/python3.5/site-packages/Xlib/ext/record.py", line 243, in enable_context
context = context)
File "/usr/lib/python3.5/site-packages/Xlib/ext/record.py", line 220, in __init__
rq.ReplyRequest.__init__(self, *args, **keys)
File "/usr/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1361, in __init__
self.reply()
File "/usr/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1373, in reply
self._display.send_and_recv(request = self._serial)
File …
```
=> Fix XRECORD extension and demo

Xlib/protocol/rq.py, Xlib/xobject/drawable.py, examples/get_selection.py, test/gen/genprottest.py, test/test_events_be.py, test/test_events_le.py, test/test_requests_be.py, test/test_requests_le.py
With the support for Python 3 we started automatically encoding/decoding 8-bits string properties. This is a mistake, as some properties are binary, and those that are actual text may use different encodings. This PR revert the change: bytes are expected on input and returned on output.
FWIU, there are 3 types of text properties:
* `STRING` for ISO-8859-1 encoded strings
* `UTF8_STRING` for UTF-8 encoded strings
* and `COMPOUND_TEXT` for [ISO/IEC 2022](https://en.wikipedia.org/wiki/ISO/IEC_2022) encoded strings
This PR add 2 convenience helpers for dealing with text properties: `change_text_property` and `get_full_text_property`, with automatic encoding/decoding for `STRING` and `UTF8_STRING`.
Those are automatically used for setting/getting `wm_name`, `wm_icon_name`, `wm_class` and …
=> Fix properties handling

Xlib/support/unix_connect.py
Unlike with Python 3, `bytes(x for x in range(4))` returns a generator object with Python 2.
Fix #53.
=> support/unix_connect: fix Python 2 support

.gitignore, Xlib/ext/composite.py
I added this function to get the overlay window.
The release function is missing since I'm not sure about how to implement it and I don't need it anyway since I'll be probably switching to C++ to do what I'm doing.
If you can, please check that I implemented it correctly (the protocol fields are 100% accurate, just not sure about the python code since there's some magic going on and I basically looked around and copy-pasted from other methods like a monkey).
=> CompositeGetOverlayWindow

Xlib/protocol/display.py
With Python >=3.3, `select.error` is now an instance of OSError.
Note that there was no issue with Python 3.5 as interrupted system calls are automatically retried.
The logic was tested with this small test script: https://gist.github.com/anonymous/3b366a4dd564c6c82a5bbf03fab50a76
=> protocol/display: fix interrupted select handling for Python 3.3/3.4

Xlib/protocol/display.py, test/test_bytesview.py
With Python 2, slicing a buffer yield new data, but with Python 3, slicing a memoryview return another memoryview:
```python
> python2 -c 'print buffer(b"12345")[1:3].decode()'
23
> python3 -c 'print(memoryview(b"12345")[1:3].decode())'
Traceback (most recent call last):
File "<string>", line 1, in <module>
AttributeError: 'memoryview' object has no attribute 'decode'
```
=> protocol/display: fix Python 3 buffer abstraction

Xlib/support/unix_connect.py
Use an abstract address if no matching filesystem path is found. This is necessary when building a [snap package](http://snapcraft.io/) using `python-xlib`.
This can also be tested with:
```shell
> Xvfb -ac :42 &
> rm /tmp/.X11-unix/X42
> DISPLAY=:42 python -c 'from Xlib import display; display.Display()'
```
=> support/unix_connect: improve Unix socket support

Xlib/support/unix_connect.py, Xlib/xauth.py
Be more lenient if `$XAUTHFILE` / `~/.Xauthority` does not exist. This fixes #66.
=> support/unix_connect: improve Xauthority handling

Xlib/support/unix_connect.py, test/test_unix_connect.py
Empirical testing and reading the implementation of Xlib/XCB show that the full format for `$DISPLAY` is: `PROTOCOL/HOSTNAME:DISPNO:SCREEN`. See the tests for valid (and invalid) use cases.
Note: this also address the problem fixed by patch 97b388a9478579b02004ac482c0a2b8364efd446 in #59.
=> support/unix_connect: improve DISPLAY handling

.travis.yml, runtests.py, tox.ini
* add helper script to run tests: `runtests.py` will handle starting `Xvfb` and running `nose` with the appropriate arguments
* add [tox](https://pypi.python.org/pypi/tox/2.5.0) configuration so it's easier to test locally for different Python versions
Note: `runtests.py` will pick different display numbers based on the Python version used, so it's possible to use [detox](https://pypi.python.org/pypi/detox/0.10.0) to run tests in parallel.
=> Rework tests handling

.travis.yml, tox.ini
* add Python 3.6 to the list of interpreters tested by tox
* add a Python 3.6 build to Travis
=> test Pyhon 3.6 too

test/test_events_be.py, test/test_requests_be.py
I regenerated `test/test_events_be.py` and `test/test_requests_be.py` under a powerpc VM. Those tests should now run fine with Python 2 and 3.
The Python versions used for testing were:
- Python 2.7.3: the whole testsuite ran fine
- Python 3.2.3: we don't official support this version, but all the big-endian specific tests passed (some other part of the testsuite failed)
This should take care of #75 and #76. @opoplawski: would you be able to check on your end?
=> test: update big-endian tests

Xlib/xobject/drawable.py
Otherwise it fails:
```python
File "/usr/local/lib/python3.5/dist-packages/Xlib/protocol/rq.py", line 688, in pack_value
data = array(array_unsigned_codes[size], val).tostring()
TypeError: 'int' object is not iterable
```
=> Fixed an error in set_wm_transient_for

.travis.yml, Xlib/xauth.py, tox.ini
Fix the following Python warning: `Xlib/xauth.py:45: ResourceWarning: unclosed file`.
Note: I've also enabled all Python warnings during Travis/tox tests run, so we can detect similar issues earlier.
=> Fix xauth unclosed file

codecov.yml, dev-requirements.txt, runtests.py, tox.ini
- add `nose` to development requirements
- runtests: fix subprocess call to run tests; make sure the correct Python interpreter is used
- tox: use requirements files to specify dependencies
- codecov: ignore examples/
=> Small tests releated improvements

NEWS, Xlib/protocol/rq.py
* fix string decoding when using Python 3: X11 text strings are encoded with the Host Portable Character Encoding, which means we should be using ASCII, the same as the default with Python 2, and not UTF-8.
* fix warnings about `array.tostring()` (deprecated)
=> improve Python 3 support

Xlib/protocol/display.py, Xlib/support/connect.py, Xlib/support/unix_connect.py, Xlib/support/vms_connect.py, dev-requirements.txt, test/test_unix_connect.py
Fallback to TCP when implicit Unix socket connection fails.
Fix #99.
=> support/unix_connect: mimic XCB behavior

Xlib/display.py
class ChangePointerControl in request.py expects 'do_thresh', but display.py file provides 'do_thres'.
from Xlib import X, XK, display
disp = display.Display()
disp.change_pointer_control((1,1),1)
returns following traceback before introducing change (aka fixing mispelling), but not after
Traceback (most recent call last):    
File "<stdin>", line 1, in <module>
File "/home/hostname/.local/lib/python3.5/site-packages/Xlib/display.py", line 820, in change_pointer_control
threshold = threshold)                   
File "/home/hostname/.local/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1347, in __init__
self._binary = self._request.to_binary(*args, **keys)             
File "/home/hostname/.local/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1004, in to_binary
raise …
=> Corrected missing last letter in variable name.

.travis.yml
Rational: 
- eggs are deprecated
- setuptools' easy_install now support installing from wheels anyway
=> travis: drop eggs from releases

Xlib/xobject/drawable.py
The deprecated `Image.tostring` method has been removed in Pillow>=3.0. Fix #105.
=> xobject/drawable: fix `put_pil_image` implementation

Xlib/protocol/rq.py
Looks like I was wrong in #92: using ASCII can cause issues (see https://github.com/openstenoproject/plover/issues/919). As it turns out character strings should be decoded using Latin-1, see for example: https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:InternAtom.
=> protocol/rq: fix string decoding

Xlib/protocol/display.py, Xlib/support/connect.py, Xlib/support/unix_connect.py
Fix #114:
- fix support for explicit unix connections
- fix macOS support
Note: I don't have a macOS machine to test, but I'm pretty sure the previous code was broken on macOS (because the protocol would be set to an empty string instead of `None`), so I reworked that part of the code also, but need someone with access to a machine to confirm it does work.
=> support/unix_connect: fix protocol handling

Xlib/protocol/display.py
When using python3, the subcode received from the response is already an
`int`, triggering a `TypeError` when attempting to decode it using `ord()`.
This patch checks the subcode type before attempting to decode it.
Fixes #119
=> fix parse_event_response subcode decoding

CHANGELOG.md, Xlib/display.py, Xlib/protocol/display.py
Move finalized classes for resource types at the instance level, to avoid creating recursive class hierarchies.
Fix #136.
=> fix increasing memory usage on display instantiation

Xlib/ext/__init__.py, Xlib/ext/damage.py, examples/xdamage.py
This example demonstrates the use of the damage extension. This simple script creates 2 windows:
1.Changing Window - continuously changes color
2.Tracking Window  - displays the changed area in the Changing Window
The area notified by the damage extension notification will be painted in the second window.
=> Damage ext example

Xlib/ext/nvcontrol.py, examples/nvcontrol.py
- Fixed bug where `get_cooler_manual_control_enabled` was returning `False` instead of `None` making not possible differentiate if manual control was actually disabled (`False`) or not possible at all (`None`) due to the Coolbit 4 not being set.
- Fixed bug where `get_gpu_nvclock_offset_range` was always returning the offset of the first power level.
- Added `get_clock_info` method and aligned method names to the respective methods from NVIDIA Management Library.
=> NV-CONTROL: bugfixes and new features

Xlib/ext/xfixes.py, examples/xfixes-selection-notify.py
These events can be used to tell when the owner of the clipboard
selection has changed.
Add an example that demonstrates usage.
=> XFixes: add XFixesSelectionNotify events

Xlib/ext/xinput.py
The existing code library generates a fatal exception:
```
File "/usr/lib/python3/dist-packages/Xlib/display.py", line 127, in __init__
mod.init(self, info)
File "/usr/lib/python3/dist-packages/Xlib/ext/xinput.py", line 652, in init
disp.ge_add_event_data(info.major_opcode, device_event, DeviceEventData)
File "/usr/lib/python3/dist-packages/Xlib/display.py", line 227, in __getattr__
raise AttributeError(attr)
AttributeError: ge_add_event_data
```
when connected to RealVNC's current xserver.
VNC(R) Server 6.4.1 (r40826) x64 (Mar 13 2019 16:27:00)
Copyright (C) 2002-2019 RealVNC Ltd.
This prevents the exception by testing for the presence of ge_add_event_data before calling it.
=> Add check for older / non-compliant X servers

Xlib/ext/nvcontrol.py
NVCtrl has a bug where it fails to set a clock offset if Xorg is running rootless, unless you use `NV_CTRL_GPU_NVCLOCK_OFFSET_ALL_PERFORMANCE_LEVELS` and `NV_CTRL_GPU_MEM_TRANSFER_RATE_OFFSET_ALL_PERFORMANCE_LEVELS`, see https://github.com/NVIDIA/nvidia-settings/issues/42.
This would allow [gwe](https://gitlab.com/leinardi/gwe) to overclock in such cases.
=> NV-CONTROL: set offset for all perf levels

Xlib/protocol/display.py
The socket.error, which is an alias to OSError since python 3.3, is not
subscriptable (and its subclasses neither are). Hence, pass the entire
exception message to close_internal().
In case of a socket.error in self.socket.send(), the former code crashed
with a TypeError.
I strongly suspect that this closes issue #127.
=> Fix TypeError in socket.error exception handling

Xlib/ext/__init__.py, Xlib/ext/dpms.py, examples/dpms.py
Based on the documentation found here: https://www.x.org/releases/X11R7.7/doc/xextproto/dpms.html
It basically works, however there are some known issues:
- Any `rq.Request` call (`dpms_enable()`, `dpms_set_timeouts()`, `dpms_force_level()`) only works if you call another `rq.ReplyRequest` function (`dpms_get_version()`, for example) afterwards. I tried to  change them to use `rq.ReplyRequest`, this worked but since they don't return anything they got stucked waiting for a response from X11. Maybe I am missing some call to another function?
- `DPMSInfo` doesn't work. I don't have a clue why, but it doesn't seem to be an issue with X11. I receive the following error when trying to call `dpms_info()`:
```
$ cat playground.py
from Xlib import display
d = display.Display() …
```
=> Add DPMS extension

Xlib/xobject/drawable.py
The Xlib/protocol/rq.py file defines an helper function encode_array()
that calls tostring() or tobytes() depending on which python version is
used.
The package maintainer Christoph Egger reported that the testsuite of
the herbstluftwm project fails[1] with the error:
```
def _get_struct_prop(self, pname, ptype, pstruct):
r = self.get_property(pname, ptype, 0, pstruct.static_size // 4)
if r and r.format == 32:
>           value = r.value.tostring()
E           AttributeError: 'array.array' object has no attribute 'tostring'
/usr/lib/python3/dist-packages/Xlib/xobject/drawable.py:782: AttributeError
```
Backtrace:
../tests/conftest.py:624: in is_window_urgent
hints = window.get_wm_hints()
/usr/lib/python3/dist-packages/Xlib/xobject/drawable.py:756: in get_wm_hints
return …
=> Use encode_array() in Drawable._get_struct_prop()

README.rst, Xlib/ext/__init__.py, Xlib/ext/res.py, examples/run_examples.py, examples/xres.py
also known as XRes or X-Resource. I needed that in an application that already relies on `python-xlib`, so I decided to upstream my findings.
Based on the xcb bindings sources and the protocol documentation:
- https://www.x.org/releases/current/doc/resourceproto/resproto.txt
- https://cgit.freedesktop.org/xcb/proto/tree/src/res.xml
Verified that all methods are working with an example application with Python 2 and 3.
Notes:
- A bit hesitant on the `protocol.rq.Object` commit. It was required to fix the exception, but maybe I'm just declaring `ResourceSizeSpec` wrong?
All tests are passing though, so at least this doesn't seem to break things.
- None of the extension methods could be moved to `window`, as it's explicitly stated in the spec that the `client` could be an ID of any resource …
=> Add Xlib.ext.res

README.rst
Originally when I tried to use this package I did not know about the OS requirement. This will leave a note about OS compatibility.
Fix #116
=> Include note about OS support

Xlib/keysymdef/xf86.py
Added keysyms:
- Suspend
- hibernate
- touchpad controls
- microphone toggle
- WWAN
- RFKill
- Audio preset
- rotation lock toggle
- full screen
- ModeLock
- MonBrightnessCycle
- LogWindowTree
- LogGrabInfo
These "new" keysyms were taken from `/usr/include/X11/XF86keysym.h` on my Ubuntu machine
=> Update xf86.py with new keysyms

Xlib/ext/xfixes.py, examples/xfixes-cursor-notify.py
These events can be used to detect when the mouse cursor changes and obtain the image of the new cursor.
Example script is also included.
References:
- https://www.x.org/releases/X11R7.7/doc/fixesproto/fixesproto.txt
- https://metacpan.org/pod/X11::Protocol::Ext::XFIXES#$X-%3EXFixesSelectCursorInput-($window,-$event_mask)%3E
-----
Notes:
While the spec doesn't have explicit padding before the last `cursor_image` struct field, I had to add a `rq.Pad(8)` or else the images were offset by a couple pixels:
```
rq.Card32('cursor_serial'),
rq.Pad(8),
rq.List('cursor_image', rq.Card32)
```
=> XFixes: add support for XFixesCursorNotify

Xlib/ext/screensaver.py
The protocol encoding specified in the X11 documentation differs from the actual XCB protocol that Xorg uses. This makes `query_version()` report the wrong version and `query_info()` fail by trying to unpack too many bytes.
=> Fix screensaver protocol mismatch

doc/src/concepts.texi
The current link (http://www.rahul.net/kenton/xsites.html) returns **403 Forbidden**, so I changed it to the last working archived version (https://web.archive.org/web/20201228053920/http://www.rahul.net/kenton/xsites.html).
=> Use archived link for X documentation resource

Xlib/xauth.py
Fixes #207.
The patch comes from a suggestion in this Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/python-xlib/+bug/1885304
I tested on a NixOS 22.05 system running GNOME 42.2. On this system, `xauth list` prints an authorization of the form `hostname/unix:` without a display number. I reproduced the issue and and validated the fix with this command:
```
nix-shell -p python3Packages.xlib --run "python -c 'from Xlib.display import Display; Display()'"
```
I'm unsure of the potential consequences of this patch, so a careful review is appreciated.
=> xauth: fix for auth entry having no display number

Xlib/display.py, Xlib/ext/damage.py, test/test_xlib_display.py
As reported in Issue #233, the xrandr functionality is unusable because of an error, which can be seen when `examples/xrandr.py` is run:
```
% python ./examples/xrandr.py
Traceback (most recent call last):
File "/home/matt/python-xlib/./examples/../Xlib/display.py", line 224, in __getattr__
function = self.display_extension_methods[attr]
KeyError: 'extension_add_error'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/matt/python-xlib/./examples/xrandr.py", line 196, in <module>
Window(display.Display()).loop()
File "/home/matt/python-xlib/./examples/../Xlib/display.py", line 127, in __init__
mod.init(self, info)
File "/home/matt/python-xlib/./examples/../Xlib/ext/randr.py", line 1291, in init …
```
=> Fix Issue 233: Rename `add_extension_error` method

Xlib/support/unix_connect.py, test/test_unix_connect.py
Hi, thanks for the great python-xlib.
I want to use this library on Windows (without WSL), so I made this PR.
If you could review and merge this, I would be happy.
This PR will make `unix_connect.get_socket` function to avoid using `fcntl` module on some environments and use [`socket.socket.set_inheritable`](https://docs.python.org/3.9/library/socket.html#socket.socket.set_inheritable) instead if possible.
[PEP446](https://www.python.org/dev/peps/pep-0446/) allows the use of `socket.socket.set_inheritable` in Python 3.4 and above versions. This seems to work basically in environments including Windows where socket module can be used. So if we can use it in an environment, we can use it to eliminate the dependency on `fcntl` module and improve the portability of python-xlib.
=> Avoid to use fcntl module on some environments
