.gitignore, Xlib/protocol/display.py
=> Minor cleanups

Xlib/protocol/rq.py
It looks like the uses of buffer() here were to do a non-copying slice - i.e. `buffer(data, p)` is equivalent to `data[p:]`, but it points to the existing memory used for data rather than copying it.
I'm proposing this change for discussion: it replaces the buffer calls with standard slicing. If bytes objects are passed in, this will copy data, with some potential performance loss - how much depends on how many times we're slicing each chunk of data. The tests are not measurably slower.
If the overhead of copying is significant, the caller of the parsing machinery can pass in a memoryview object, on which slices should be non-copying. I think this should mostly work with no changes to this code, but if that's important, we should obviously test it.
This reduces the number of test failures …
=> Remove some uses of buffer()

Xlib/display.py
These changes were necessary to run the draw.py example.
=> Fix imports in Xlib.display

.travis.yml, Xlib/protocol/display.py, Xlib/support/connect.py, Xlib/support/unix_connect.py, Xlib/xauth.py, Xlib/xobject/colormap.py, Xlib/xobject/cursor.py, Xlib/xobject/drawable.py, Xlib/xobject/fontable.py, test/test_xlib_display.py
=> Unit tests for display.py

test/gen/genprottest.py, test/test_events_be.py, test/test_events_le.py, test/test_requests_be.py, test/test_requests_le.py, test/test_xlib_display.py
As a small follow-up to #28, remove some unused imports.
=> test: remove unused imports

Xlib/ext/xinput.py
Add support for:
* `grab_device/ungrab_device` requests
* `grab_keycode/ungrab_keycode` requests
* `query_device` request
*  `ButtonPress/ButtonRelease/KeyPress/KeyRelease/Motion` device events
* `DeviceChanged` event
=> improve XInput support

setup.py
Also get rid of code for Python <2.3.3 support.
=> setup: update download/project URLs

.landscape.yml
* enable Python 3 support
* disable support for the mccabe tool to prevent decoding errors when parsing Xlib/protocol/display.py
=> landscape: add configuration

Xlib/ext/shape.py, examples/shapewin.py
Replace with a version generated form xcb-proto.
=> shape: rewrite extension

Xlib/ext/shape.py, examples/shapewin.py
* fixup `ShapeNotify` event handling
* update and fix example
=> fixup shape extension support

examples/run_examples.py, examples/xlsatoms.py
- fix Python 3 support
- fix default display
- enable it in run_examples.py
=> examples: fix xlsatoms

.travis.yml, setup.cfg
Create only one [universal wheel](https://packaging.python.org/distributing/#universal-wheels).
=> setup: create a universal wheel

doc/html/texi2html, examples/draw-proto.py, examples/draw.py
Cherry pick from #59:
* [Fix spelling of rhomboid](https://github.com/python-xlib/python-xlib/pull/59/commits/16851944642a8d1ab9ca6c0f1f22b405560b9f31)
* [Fix perl usage](https://github.com/python-xlib/python-xlib/pull/59/commits/ea4d2fe9d82d85691a28a1183b6939bb216b55bf)
=> Cherry pick from #59

Xlib/protocol/display.py
Improve performance for large responses by calling `socket.recv` with an increased size:
- calculate default size according to socket parameters
- if we know it, take into account current response size and how much data is needed to get the complete response
Fix  #86.
=> protocol/display: improve response processing

setup.py
=> setup: check setuptools is recent enough to support `setup.cfg`

Xlib/display.py, Xlib/ext/xinerama.py, Xlib/protocol/display.py, Xlib/protocol/rq.py, Xlib/rdb.py, debian/rules, doc/src/errors.texi, doc/src/events.texi, doc/src/objects.texi, examples/get_selection.py
Some misspellings:
- in comments
- in code
=> Simple misspellings

Xlib/ext/composite.py
This pull request adds the ability to setup error handlers for all composite extension functions that can throw X errors.
https://www.x.org/releases/X11R7.5/doc/compositeproto/compositeproto.txt
=> ext: composite: add error handlers

Xlib/protocol/rq.py
tested with py2 2.7 and py3 3.5
=> fix py3 crash sample at rosettacode.org/wiki/Window_creation/X11#Xlib_2

examples/xdamage.py
Tested on Python 3.7 and 2.7.16.
=> Xdamage example fixes

.travis.yml
https://devguide.python.org/#status-of-python-branches
https://devguide.python.org/devcycle/#end-of-life-branches
=> Travis CI: Add Python 3.7 and 3.8 to the testing

Xlib/ext/dpms.py, examples/dpms.py
Sorry, I typed my e-mail wrong and didn't saw until now :disappointed: .
=> Fix e-mail in DPMS extension

Xlib/protocol/rq.py, Xlib/xobject/resource.py
Reprs should contain the name of the class not the class's whole string conversion.
<class SomeClass>(args)  ->  SomeClass(args)
=> Fix __repr__s

.travis.yml, CHANGELOG.md, Xlib/__init__.py, Xlib/ext/xinput.py
=> Updates for Python 3.9 support

doc/src/objects.texi
=> Fix minor typo in documentation

.gitignore, Xlib/ext/xinput.py
Hello!
Please approve my improvements with the xinput extension. I can add some examples if need.
**Updates:**
- new method `xinput_list_device_properties`
- new method `xinput_get_device_property` 
- new method `xinput_change_device_property`
- new method `xinput_delete_device_property`
- added data object for `PropertyEvent`
=> Xinput device properties improvements

Xlib/ext/composite.py, Xlib/ext/damage.py, Xlib/ext/dpms.py, Xlib/ext/randr.py, Xlib/ext/record.py, Xlib/ext/xfixes.py, Xlib/ext/xinerama.py, Xlib/protocol/rq.py, Xlib/xobject/drawable.py
Found a handful of unused imports.
The dependency on tkinter was also unnecessary as it was only importing a single constant (which is not even used by Xlib). ~~I kept the constant so this doesn't count as a breaking change (idk if it's meant to be part of the protocol).~~
Fixes #240
=> Removed unused imports

LICENSE
... to match https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt.
=> Change parentheses to brackets in LICENSE
